config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#index'
  resources :posts
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    
  @posts = Post.all
    
  end

  
    def new
      @post = Post.new
    end
      
      def create
        Post.create( post_params )
        redirect_to posts_path
      end
      
      private
      
      def post_params
        params.require(:post).permit(:title, :description, :image)
        
      end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixter</title>
 
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
     
      
      <%= link_to 'pixter', root_path, :class => 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
          <li>
           
            <%=link_to 'create', new_post_path %>
            </li>
          <li>
            <%=link_to 'posts', posts_path %>
            </li>
        </ul>  
      </div>
 
    </div>
  </div>
</div>


<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="private-square span4">
   <h1>
    <%= post.title %>
    </h1>
    <%= image_tag post.image %>
    
    <h2>
      <%= post.description %>
    </h2>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="private-square span 4 offset2">
  <h1> upload your image </h1>
  <%= simple_form_for @post do |f| %>
  <%= f.input :title, label: 'who is this?', placeholder: 'eg. Riker, Data, Jordy, Scotty...' %>
  <%= f.input :description, label: 'where is this image?', placeholder: 'eg. Riker is happy, etc.' %>
  <br/>
  <%= f.input :image %>
  <br/>
  <%= f.button :submit, :class => 'btn btn-success btn-large' %>
  <% end %>
            </div>

app/views/static_pages/index.html.erb
<div class="private-square span 6 offset 2">
  <h1>
    
    My awesome App is here!
      
  </h1>
  
  <br/>
  <%= link_to 'Launch', posts_path, :class => 'btn btn-info btn-large' %>
  
    
  <h2>
      
   
      
  </h2>
</div>